### ISSUE TITLE
Example seems to be broken

### ISSUE THREAD

**Issue by james-masson** [testable/wdio-testable-example#1]
```
jmasson@xps15 ~/performance-tests $ npx wdio

[11:14:51]  COMMAND POST     "/session"
[11:14:53]  COMMAND POST     "/session/4b9d476a-ddb2-42b4-8fa4-e504dc564adc/url"
F[11:14:55]  COMMAND    DELETE   "/session/4b9d476a-ddb2-42b4-8fa4-e504dc564adc"
/home/jmasson/performance-tests/node_modules/webdriverio/build/lib/utils/RequestHandler.js:269
                        var errorCode = _constants.ERROR_CODES[body.status] || _constants.ERROR_CODES[body.value.error] || _constants.ERROR_CODES[-1];
                                                                                                                 ^

TypeError: Cannot read property 'error' of null
    at Request._callback (/home/jmasson/performance-tests/node_modules/webdriverio/build/lib/utils/RequestHandler.js:269:114)
    at Request.self.callback (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)


0 passing (4.90s)
1 failing

1) A basic test should be possible to go to google:
Cannot read property 'error' of null
running firefox
TypeError: Cannot read property 'error' of null
    at Request._callback (/home/jmasson/performance-tests/node_modules/webdriverio/build/lib/utils/RequestHandler.js:269:114)
    at Request.self.callback (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/jmasson/performance-tests/node_modules/webdriverio/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

```

I suspect this is because you require an obsolete version of webdriverio.

**Comment by avistramer** [comment]
I assume you're not just running the example with the package.json and wdio conf provided? Because I see the error references firefox and the example is configured for Chrome. It seems to work fine for me. 

It was written for wdio 4.x so if you're trying with 5.x it might not work. 5.x was only released a couple of months ago so we don't yet support it, though soon!

**Comment by james-masson** [comment]
I'm running the package.json provided, and a tweaked wdio.conf to talk to my local geckodriver.

Interestingly, if I bump to the latest webdriverio v4.14 it works - just not the version "4.8.0" you specify.

**Comment by avistramer** [comment]
Ah yea I see what you mean, it seemed to work with Chrome even with the older versions. I updated the dependencies to the latest for 4.x just now. Thanks for pointing this out!
